[project]
name = "nyc-taxi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "click>=8.3.1",
    "jupyter>=1.1.1",
    "pandas>=3.0.0",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.46",
    "tqdm>=4.67.2",
]
